name: Push-to-ec2
on:
  push:
    branches:
      - Master
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the files
      uses: actions/checkout@v3

    - name: Copy files with ssh
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        #ARGS: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
        SOURCE: "./"
        REMOTE_HOST: "ec2-3-231-252-126.compute-1.amazonaws.com"
        REMOTE_USER: "ubuntu"
        TARGET: "/home/ubuntu/"
        #EXCLUDE: "/venv/,/.git/"
        #